project:
  type: website

website:
  title: "Yihan Wang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research & Code
      - href: slides.qmd
        text: Teaching
      - href: presentations.qmd
        text: Presentations
      - href: about.qmd
        text: About
  page-footer:
    center: "© 2026 Yihan Wang"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    link-external-newwindow: true