---
title: "Conference Presentations"
---

Wang, Y., Matz, C., Miller, J., Carr, D. C., & Kohlbacher, F. (November 2018). Uses and gratifications sought from mobile phone use and loneliness among Japanese older adults: a mediation analysis. **Gerontological Society of America Annual Conference**, Boston.

Wang, Y., Woo, B., & Jiang, N. (2018). A systematic review of risk and protective factors of loneliness among Asian immigrants in the U.S.: An ecological approach. **Gerontological Society of America Annual Conference**, Boston.

Wang, Y. & Wang, Y. (August 2018). Productive activities and loneliness among middle-aged and older Japanese. **International Federation on Ageing 14th Global Conference**, Toronto.

Wang, Y., Matz, C., Miller, J., Carr, D. C., & Kohlbacher, F. (August 2018). Uses and gratifications sought from mobile phone use and mental health outcomes among Japanese older adults. **International Federation on Ageing 14th Global Conference**, Toronto.

Easton, S. D., Safadi, N. S., Crea, T. M., Hasson, R. G., & Wang, Y. (2018). Health and well-being of public sector social workers in occupied Palestinian territories. A technical report presented for the **Ministry of Social Development, Palestinian National Authority**. Online.

Wang, Y. (June 2018). Managing elder care in China and the United Kingdom: Aging workforce from the East and West. **Work and Family Researchers Network (WFRN)**, Washington DC.

Wang, Y., Easton, S. D., Safadi, N. S., & Hasson, R. G. (January 2018). The Kessler psychological distress scale: translation and validation of an Arabic version. **Society for Social Work and Research (SSWR)**, Washington DC.

Safadi, N. S., Easton, S. D., Wang, Y., & Hasson, R. G. (January 2018). Life and job satisfaction among public sector social workers in the occupied Palestinian territories. **Society for Social Work and Research (SSWR)**, Washington DC.

Wang, Y. & Matz, C. (July 2017). Health and well-being of retirees: Roles of social interaction and exchange reciprocity. **World Congress of Gerontology and Geriatrics**, San Francisco.

Wang, Y. & Gonzales, E. (November 2016). Intergenerational caregiving and mental health: Findings from the CHARLS. **Gerontological Society of America**, New Orleans.

Wang, Y. (November 2015). Transitioning from institutional care to community-based care: Case examples from the United States and Japan. **Gerontological Society of America**, Orlando.